services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: pomodoro

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
