"""delete_comment

Revision ID: be1abcd26c8e
Revises: aed215ee853e
Create Date: 2025-03-26 12:44:43.782538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1abcd26c8e'
down_revision: Union[str, None] = 'aed215ee853e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'comment')
    op.drop_column('UserProfile', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('UserProfile', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
